stages:
  - test
  # - sonar

image: node:18.16.0

cache:
  paths:
    - node_modules/

test:
  stage: test
  before_script:
    - npm set progress=false
    - npm ci  --cache .npm --prefer-offline
  script:
    - npm install
    - npm run lint
  only:
    - merge_requests

# sonarqube-check:
#   stage: sonar
#   image: sonarsource/sonar-scanner-cli
#   allow_failure: false
#   script:
#     - sonar-scanner -X -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=$CI_PROJECT_NAME -Dsonar.projectName=$CI_PROJECT_NAME

